spring:
    datasource:
      url: jdbc:mysql://192.168.245.220:3306/springbootdemo
      username: springbootdemo
      password: Yqqlm!Gs1cl$
      schema: database/import.sql
      sql-script-encoding: utf-8
      driver-class-name: com.mysql.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

    thymeleaf:
       cache: false
       mode: LEGACYHTML5