spring:
    datasource:
      url: jdbc:mysql://192.168.245.220:3306/springbootdemo
      username: springbootdemo
      password: Yqqlm!Gs1cl$
      #schema: database/import.sql
      #sql-script-encoding: utf-8
      driver-class-name: com.mysql.jdbc.Driver

    jpa:
      database: mysql
      show-sql: true
      hibernate:
        ddl-auto: update
        # hibernate.hbm2ddl.auto节点的值有几个create、create-drop、update、validate、none
        # create：每次加载hibernate会自动创建表，以后启动会覆盖之前的表----不要使用
        # create-drop ： 每次加载hibernate时根据model类生成表，但是sessionFactory一关闭，表就自动删除，下一次启动会重新创建----不要使用
        # update：加载hibernate时根据实体类model创建数据库表，
        #   这是表名的依据是@Entity注解的值或者@Table注解的值，sessionFactory关闭表不会删除，
        #   且下一次启动会根据实体model更新结构或者有新的实体类会创建新的表。
        # validate：启动时验证表的结构，不会创建表
        # none：启动时不做任何操作
        naming:
          strategy: org.hibernate.cfg.DefaultComponentSafeNamingStrategy
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL5Dialect

#    jackson:
#      serialization:
#        indent_output: false

    thymeleaf:
       cache: false
       mode: LEGACYHTML5